DROP DATABASE IF EXISTS calendar_db;
CREATE DATABASE calendar_db;

CREATE TABLE schedule
(
    id INT NOT NULL AUTO_INCREMENT,
    day VARCHAR(100) NOT NULL,
    appointment VARCHAR(250) NOT NULL,
    apt_time VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
)